### PR TITLE
Update URLs from Google Code to Github

### PR DESCRIPTION
**Pull request by j3parker**

### CODE REVIEW

**Comment by j3parker** [comment]
I signed it.

**Comment by j3parker** [comment]
The only remaining mention from [the source](https://github.com/google/gitiles/search?utf8=%E2%9C%93&q=%22code.google.com%22) is fine.

**Comment by j3parker** [comment]
FYI :)
(I don't really care, it's just in my list of open PRs)

**Comment by ePirat** [comment]
It seems like this repo is not updated anymore, instead https://gerrit.googlesource.com/gitiles/ is.

**Comment by j3parker** [comment]
Ah cool, and someone updated the links to point there and the new version has been deployed, great.

**Pull request closed without merging**
