### PR TITLE
Update capitalization

### PR DESCRIPTION
**Pull request by DamieFC**
Change "github" to "Github".

### CODE REVIEW

**Comment by DamieFC** [comment]
@googlebot I signed it!

**Comment by DamieFC** [comment]
@googlebot  I signed it!

**Comment by DamieFC** [comment]
I signed it!

**Comment by DamieFC** [comment]
I quit

**Comment by krystian3w** [comment]
> This project doesn't take pull requests. See https://gerrit.googlesource.com/gitiles/+/HEAD/Documentation/developer-guide.md for contribution instructions.

**Pull request closed without merging**
